### ISSUE TITLE
"Please refresh the page"

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/OnlyFans#1247]
I'm getting this error:

> Auth (V1) Attempt 1/10
> Please refresh the page
> Scraping Paid Content
> Scraping Subscriptions
> There's nothing to scrape.
> Archive Completed in 0.0 Minutes
> Pausing scraper for 0 seconds.

I think it might have to something to do with the fact that OnlyFans just changed its layout.

**Comment by misterscraper** [comment]
I can confirm I'm getting the same issue

**Comment by freakish804** [comment]
yeah same issue

**Comment by Macmasteri** [comment]
Same here as well. using geckodriver.

**Comment by atlas-mugged** [comment]
Same issue here on ubuntu 20.04

**Comment by Gixxa** [comment]
Got the same error and if someone from onlyfans is reading this the design sucks...

**Comment by misterscraper** [comment]
> Newest commit fixed it for me.

confirm issue has been fixed now :)

**Comment by atlas-mugged** [comment]
confirm fixed aswell after updating

**Comment by Macmasteri** [comment]
Do you guys use geckodriver or fill in information manually?

Been trying to fill auth-id and session with no luck. Is x-bc neccesary?

**Comment by Gixxa** [comment]
@Macmasteri 

I fill it in manually, as I'm still having this issue --> #1121 

I'm currently downloading but I'll test if it works with e-mail and password later and edit this post.

**Comment by Macmasteri** [comment]
> @Macmasteri
> 
> I fill it in manually, as I'm still having this issue --> #1121
> 
> I'm currently downloading but I'll test if it works with e-mail and password later and edit this post.

Good. What information you fill in?

**Comment by Gixxa** [comment]
@Macmasteri 

"username": "default",
"auth_id": "123456789",
"sess": "123abc....",
"user_agent": ".....",
"x_bc": "123abc....",

Don't download the version from "Releases" but from the "Code" button.

**Comment by Macmasteri** [comment]
> @Macmasteri
> 
> "username": "default",
> "auth_id": "123456789",
> "sess": "123abc....",
> "user_agent": ".....",
> "x_bc": "123abc....",
> 
> Don't download the version from "Releases" but from the "Code" button.

Tried this and with no luck. Used chrome and now firefox and cant find x-bc.

Using latest commit.

**Comment by 666diabolus** [comment]
the issue is back again @DIGITALCRIMINAL 

Auth (V1) Attempt 1/10
Please refresh the page
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.01 Minutes
Pausing scraper for 0 seconds.

**Comment by simonchin513** [comment]
> the issue is back again @DIGITALCRIMINAL
> 
> Auth (V1) Attempt 1/10
> Please refresh the page
> Scraping Subscriptions
> There's nothing to scrape.
> Archive Completed in 0.01 Minutes
> Pausing scraper for 0 seconds.

Can confirm ><

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed within 30 mins

**Comment by kotsip** [comment]
Again here.
/OnlyFansScrape# poetry run python3 start_us.py
[2023-12-28 22:27:18] Assigning Jobs
[2023-12-28 22:27:18] Archive Completed in 0.0 Minutes
[2023-12-28 22:27:18] Now exiting
