### ISSUE TITLE
Auth loop

### ISSUE THREAD

**Issue by mathieut** [DIGITALCRIMINAL/OnlyFans#143]
Hi,

The script was working fine until a couple days ago where I get an auth loop for onlyfans:
```
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
```
Even after refreshing my config file, I get the same error. Anybody else?

Thanks!

**Comment by Sundune** [comment]
Check Releases Tab. There are new versions available that fix this issue.

**Comment by mathieut** [comment]
I did try the latest version and I am getting other issues:
```
Traceback (most recent call last):
  File "/Users/xxx/OnlyFans-master 2/StartDatascraper.py", line 1, in <module>
    from modules.helpers import update_config
  File "/Users/xxx/OnlyFans-master 2/modules/helpers.py", line 15, in <module>
    json_config = json.load(open('settings\\config.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'settings\\config.json'
```
My config file is there and I filled it in.

**Comment by pcjamesy** [comment]
That's what i noticed with the latest release. It's not pulling info from the config file. First asks for the site i want to scrape, followed by asking for all the config info. The config file is there and updated on my side.

**Comment by DIGITALCRIMINAL** [comment]
Are you all using linux?

**Comment by pcjamesy** [comment]
Windows subsystem for linux

**Comment by DIGITALCRIMINAL** [comment]
@pcjamesy have you tried running it on Windows?

**Comment by mathieut** [comment]
I am on macOS.

**Comment by DIGITALCRIMINAL** [comment]
Fixed in the latest commit. Reopen if you've got more problems.

**Comment by DIGITALCRIMINAL** [comment]
If you st

**Comment by DIGITALCRIMINAL** [comment]
If you still get the loop, its a cookie issue.

**Comment by Addest3** [comment]
Had the same issue. I uninstalled the old version using pip uninstall and installed the new version and cleared my cookies. Works fine now.

**Comment by mathieut** [comment]
You cleared your cookies in the browser you used to get the config info?

**Comment by DIGITALCRIMINAL** [comment]
@mathieut @mathieut I pushed a few commits about 30 minutes ago. I dunno if it works for you.

**Comment by mathieut** [comment]
Now it works but I get the following error after it starts downloading content:
```
Scraping [video | stream | gif]. Should take less than a minute.
Traceback (most recent call last):
  File "/Users/xxx/Downloads/OnlyFans-master/StartDatascraper.py", line 147, in <module>
    result = x.start_datascraper(
  File "/Users/xxx/Downloads/OnlyFans-master/modules/onlyfans.py", line 57, in start_datascraper
    results = media_scraper(
  File "/Users/xxx/Downloads/OnlyFans-master/modules/onlyfans.py", line 307, in media_scraper
    results = format_media_set(location[0], pool.starmap(scrape_array, product(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/xxx/Downloads/OnlyFans-master/modules/onlyfans.py", line 244, in scrape_array
    file_path = reformat(directory[0][1], file_name,
  File "/Users/xxx/Downloads/OnlyFans-master/modules/helpers.py", line 41, in reformat
    text = BeautifulSoup(text, 'lxml').get_text().replace(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bs4/__init__.py", line 225, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by DIGITALCRIMINAL** [comment]
```pip install lxml```

**Comment by mathieut** [comment]
I just did that and while it worked:
`Successfully installed lxml-4.5.0`
I still get the same error.

**Comment by DIGITALCRIMINAL** [comment]
Probably installed it with the wrong python version
