### ISSUE TITLE
AVNStars Error 

### ISSUE THREAD

**Issue by ctrlcmdshft** [DIGITALCRIMINAL/OnlyFans#417]
When attempting to scrape content

```
Scraping [photo]. Should take less than a minute.
2020-09-13 23:00:07,428 ERROR errors format_media_set() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "F:\OnlyFans-5.4\datascraper\main_datascraper.py", line 237, in start_datascraper
    result = x.start_datascraper(
  File "F:\OnlyFans-5.4\modules\starsavn.py", line 95, in start_datascraper
    results = prepare_scraper(
  File "F:\OnlyFans-5.4\modules\starsavn.py", line 348, in prepare_scraper
    results = format_media_set(location[0], x)
TypeError: format_media_set() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "F:\OnlyFans-5.4\datascraper\main_datascraper.py", line 237, in start_datascraper
    result = x.start_datascraper(
  File "F:\OnlyFans-5.4\modules\starsavn.py", line 95, in start_datascraper
    results = prepare_scraper(
  File "F:\OnlyFans-5.4\modules\starsavn.py", line 348, in prepare_scraper
    results = format_media_set(location[0], x)
TypeError: format_media_set() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\OnlyFans-5.4\start_ofd.py", line 9, in <module>
    main_datascraper.start_datascraper()
  File "F:\OnlyFans-5.4\datascraper\main_datascraper.py", line 257, in start_datascraper
    input()
KeyboardInterrupt
```

**Comment by ctrlcmdshft** [comment]
Anyone know how i can get passed this error

**Comment by DIGITALCRIMINAL** [comment]
I'll fix it today

**Comment by evlsmurf** [comment]
> 
> 
> I'll fix it today

Thank you!

**Comment by ctrlcmdshft** [comment]
> 
> 
> I'll fix it today

Thank you!

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed in the latest commit

**Comment by ctrlcmdshft** [comment]
```
Traceback (most recent call last):
  File "F:\OnlyFans-5.4\start_ofd.py", line 2, in <module>
    import tests.main_test as main_test
  File "F:\OnlyFans-5.4\tests\main_test.py", line 4, in <module>
    import helpers.main_helper as main_helper
  File "F:\OnlyFans-5.4\helpers\main_helper.py", line 16, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

**Comment by DIGITALCRIMINAL** [comment]
Run the requirements again

**Comment by ctrlcmdshft** [comment]
Ran requirements again and still having issues with AVNStars 
```
Scraping [photo]. Should take less than a minute.
2020-09-30 15:55:13,072 ERROR errors format_media_set() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "F:\OnlyFans-5.4\datascraper\main_datascraper.py", line 237, in start_datascraper
    result = x.start_datascraper(
  File "F:\OnlyFans-5.4\modules\starsavn.py", line 95, in start_datascraper
    results = prepare_scraper(
  File "F:\OnlyFans-5.4\modules\starsavn.py", line 348, in prepare_scraper
    results = format_media_set(location[0], x)
TypeError: format_media_set() takes 1 positional argument but 2 were given
```

**Comment by DIGITALCRIMINAL** [comment]
Because you're still using 5.4

Download the latest commit and overwrite the files

**Comment by ctrlcmdshft** [comment]
got it my bad guess i didnt overwrite all files working now but only downloading a small amount of videos and images that are posted

**Comment by DIGITALCRIMINAL** [comment]
What is your filename format

**Comment by ctrlcmdshft** [comment]
"{file_name}.{ext}",

**Comment by DIGITALCRIMINAL** [comment]
I don't have any subscriptions on AVN to test

**Comment by ctrlcmdshft** [comment]
https://stars.avn.com/avnawards is free and has a ton on content posted and same issues with that profile too

**Comment by DIGITALCRIMINAL** [comment]
Yeah, I already did all of it. It's able to download the free posts, but not the locked posts. I don't have any subscriptions to test it.

**Comment by ctrlcmdshft** [comment]
Is there a way I can donate to you the cost of a sub to fix this issue

**Comment by DIGITALCRIMINAL** [comment]
Do you have Bitcoin or any crypto?

**Comment by ctrlcmdshft** [comment]
Unfortunately I don’t

**Comment by ctrlcmdshft** [comment]
> 
> 
> Do you have Bitcoin or any crypto?

i got some bitcoin i can send you now whats the address

**Comment by DIGITALCRIMINAL** [comment]
Email me and I will tell you

**Comment by ctrlcmdshft** [comment]
> 
> 
> Email me and I will tell you

email is sent

**Comment by DIGITALCRIMINAL** [comment]
Thank you, I'm gonna fix it

**Comment by DIGITALCRIMINAL** [comment]
Should be fixed now
